version: '2'
services:
  web:
    image: week2-web-v2board:latest
    ports:
     - "8080:80"
    depends_on:
     - db
     - redis
  db:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=v2board
   ports:
     - "3306:3306"
  redis:
   image: redis:7-alpine
