version: "1.0"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    depends_on:
     - db
  db:
   image: mysql:5.7
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=gopher_shop
   ports:
     - "3306:3306"
